services:
  posteio:
    image: analogic/poste.io
    hostname: mail.vaxelaire.fr
    container_name: posteio
    environment:
      - TZ=Europe/Paris
      - HTTPS=OFF
      - HTTP_PORT=8080
      # - DISABLE_CLAMAV=TRUE # To disable ClamAV, it is useful for low mem usage.
      # - DISABLE_RSPAMD=TRUE # To disable Rspamd, it is useful for low mem usage.
      # - DISABLE_ROUNDCUBE=TRUE # To disable Roundcube webmail.

    ports:
      - 993:993
      - 995:995
      - 4190:4190
      # - 8080:8080
      - 587:587
      - 565:565
      - 465:465
      - 143:143
    volumes:
      - ./data/posteio:/data
      - ../Reverse-Proxy/data/certbot/acme-challenge/.well-known/:/opt/www/.well-known:ro
    networks:
      - mail-out
networks:
  mail-out:
    name: mail-out
    driver: bridge
    external: true
